### ISSUE TITLE
Validador Manobra: Mensagens de erro

### ISSUE THREAD

**Issue by emidioerosa** [pjefika/fulltestAPI#100]
A exemplo da versão anterior, se faz necessário alterar as frases de erro em conformidade com  os erros apresentados:

- Validador deu erro para um dslam Teledata mas não acusou que esse dslam não é trabalhado pelo efika, apresentou uma mensagem de erro genérica. 
- Informações de TBS não foram encontradas na pesquisa de cadastro.  Erro de cadastro não foi reportado, o validador retornou um erro genérico

**Comment by henmerlin** [comment]
- Testar exceções:
  - DSLAM não implementado;
  - Erro de Cadastro;
  - Ordem inválida.
