### ISSUE TITLE
Correções de lógica

### ISSUE THREAD

**Issue by emidioerosa** [pjefika/fulltestAPI#22]
Sugiro que quando a ferramenta não encontrar a instância no WISE e este mostrar a mensagem:  "Designador de Banda Larga não foi encontrado. ", ela deve mostrar para o operador duas opções:
Técnico deseja mannobra motivo Banda Larga: { } Sim {} Não 

 Para o SIM : mostra a mensagem: "Não foi encontrado designador Banda Larga para esta instância. Favor informar a instância com Banda Larga Associada".

Para o NÃO: seguir fluxo de validação de manobrta motivo Linha. Caso ainda não tenhamos esse fluxo desenvido, deve-se mostrar a mensagem do descrita no ISSUE 2 para defeito de Linha

**Comment by emidioerosa** [comment]
Para o motivo "Sem autenticação", inserir resultado da análise de rede:
Não consideraremos o resultado da análise para o cálculo da decesão, apenas mostraremos o resultado, assim o operador terá uma orientação a mais para o técnico.

**Comment by henmerlin** [comment]
@emidioerosa para cumprir este requisito teremos que realizar mudança na arquitetura da aplicação,  precisamos de um pacote para incluir esta melhoria na ferramenta. Nossa próxima **sprint** motivará esta mudança, pois trabalharemos com as centrais de linha, e clientes sem banda larga deverão ser consultados na ferramenta normalmente.
