### ISSUE TITLE
Verificação de Falha

### ISSUE THREAD

**Issue by emidioerosa** [pjefika/fulltestAPI#23]
Alumas instância estão apresentando a mensagem "Erro ao buscar cadastro" mesmo quando a pesquisa no WISE TOOL a encontra. É preciso mapear a causa.
Exemplo:

Instância 1935799143   
8-2HFOIMIO

**Comment by Agibert** [comment]
Identificado que no Wise Tool não aparecem as informações de tecnologia de voz nem de tv. Validações de  vlans são baseadas nestas informações, portanto a ausência delas é entendida como "Erro ao buscar cadastro". Necessário refatoramento, talvez definir como Sip e Híbrido quando estiver vazio.
