### ISSUE TITLE
Apresentação da tela de abertura

### ISSUE THREAD

**Issue by emidioerosa** [pjefika/fulltestAPI#24]
Sugiro uma alteração na tela de abertura indicando que o operador está na tela do validador de manobra.
Além de dar a certeza para o usuário de que ele está na opção correta,  vai ajudar a equipe de qualidade na análise de monitoria.
Em anexo segue um exemplo (somente um exemplo).

**Comment by henmerlin** [comment]
Segue exemplo de resolução:
![image](https://cloud.githubusercontent.com/assets/4692243/25856122/7210d5fc-34ab-11e7-8ed9-625aafd2babe.png)
