### ISSUE TITLE
Erros para verificação

### ISSUE THREAD

**Issue by emidioerosa** [pjefika/fulltestAPI#31]
Casos em que os erros estão ocorrendo ainda hoje. Favor identificar o motivo.
Sugestão: copiar o texto abaixo e lançar em planilha excel

Instância	Data	Falha	COD SS	Status do erro  em 16/05	WISE	Validação realizada?
1133700917	11/05/2017	Erro ao buscar cadastro	8-2JRNK7A1	Confirmado	Normal	Não
1935799143	03/05/2017	Erro ao buscar cadastro	8-2HFOIMIO	Confirmado	Normal	Não
2138445374	11/05/2017	Erro ao buscar cadastro	8-A2E86532631-1	Confirmado	Normal	Não
4132325052	11/05/2017	Erro ao realizar validações	8-A2E3CA07A0F-1	Confirmado	Normal	Não

**Comment by henmerlin** [comment]
1133700917	(Erro de cadastro)
1935799143	(Informações de Tecnologia de Voz, Tecnologia de Acesso, Rede Acesso e Tipo Central em branco) - **investigar**
2138445374 (Execeção Efika - model.dslam.factory.exception.DslamNaoImplException: Dslam não implementado) - **Vendor ZHONE MXKVDSL24 não recebendo implementação correta na Fabrica de DSLAMs - correção efetuada**
4132325052	(Teste executado com sucesso);
