### ISSUE TITLE
Alteração Validação de Velocidade Fora do Padrão

### ISSUE THREAD

**Issue by emidioerosa** [pjefika/fulltestAPI#32]
Favor alterar a regra 
DE: A manobra só é permitida se sincronismo estiver fora e a atenuação de UP estiver em 0

PARA: Se sincronismo estiver fora e uma ou ambas as atenuações estiverem em 0, a manobra será permitida.

OBS: A regra de pacotes permanece, porém a principal validação é a PARA

**Comment by henmerlin** [comment]
**Aceite:** Se qualquer atenuação estiver 0 em caso de sincronismo fora do padrão a manobra deverá ser permitida.
