### ISSUE TITLE
Sugestão de melhoria no campo de inserção de Instância 

### ISSUE THREAD

**Issue by emidioerosa** [pjefika/fulltestAPI#33]
Favor analisar a possibilidade de se permitir, no campo Instância, números contendo espaços no final e no início do texto.
Dessa forma, mesmo que o operador insira uma valor de instânica contendo espaços, a ferramenta obterá sucesso em buscar as informações.
Hoje se colar a instância com espaço no início ou no fim do texto, a ferramenta acusa ERRO AO BUSCAR CADASTRO

**Comment by henmerlin** [comment]
Requisito explicado em #35.
