### ISSUE TITLE
Unificação do ambiente de consulta

### ISSUE THREAD

**Issue by Agibert** [pjefika/fulltestAPI#42]
# Backlog Item: Unificação do ambiente de consulta

### User Story
Eu, enquanto **Operador**, quero prestar atendimento ao técnico de campo através de uma interface única para todos os fabricantes GPON.

### Critérios de Aceitação
1. A interface deve prover acesso ao: #37, #38, #41  e #46.

**Comment by henmerlin** [comment]
Bora prototipar? @pjefika/dev

**Comment by henmerlin** [comment]
Solução desenvolvida em Angular 2 em: https://github.com/pjefika/FulltestNode
