### ISSUE TITLE
Adequação Motor Massivo – Fibra Atenuada

### ISSUE THREAD

**Issue by Agibert** [pjefika/fulltestAPI#43]
# Backlog Item: Adequação Motor Massivo – Fibra Atenuada

### User Story
Eu, enquanto **BackOffice**, quero consultar clientes de forma massiva as placas GPON para distribuição de relatórios de Fibra Atenuada.

### Critérios de Aceitação
1. Definir com Edson.

**Comment by henmerlin** [comment]
Vamos fazer hoje sem falta com o Edson.

**Comment by Agibert** [comment]
Efetuar a varredura por placa.
